/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerCard: typeof import('./src/components/AnswerCard.vue')['default']
    ArticleText: typeof import('./src/components/ArticleText.vue')['default']
    CitationList: typeof import('./src/components/CitationList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    ErrorPanel: typeof import('./src/components/ErrorPanel.vue')['default']
    FeeCard: typeof import('./src/components/FeeCard.vue')['default']
    LawyerCards: typeof import('./src/components/LawyerCards.vue')['default']
    NavTree: typeof import('./src/components/NavTree.vue')['default']
    QuestionBox: typeof import('./src/components/QuestionBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
  }
}
