"""
pdf_content_english.py — 英语（english）领域的 35 个分节素材，供 generate_test_pdfs.py 渲染。

由 pdf_content.py 拆出，以免单文件过长；元组字段结构见 pdf_content.py 的模块说明。
"""

from __future__ import annotations

ENGLISH = {
    "title": "英语语法精讲",
    "subtitle": "面向中文母语学习者的语法要点与常见错误分析",
    "sections": [
        # source: https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/present-tense
        ("第一讲 英语时态总览",
         "英语时态由时间和体（aspect）两个维度构成。时间分为过去、现在和将来，体分为一般、进行、完成和完成进行，组合形成12种时态。|British Council指出，英语严格意义上只有过去时和现在时两个时态，将来时通过情态动词will表示。但教学上通常仍按12种时态讲解。|掌握各时态的核心用法和典型时间状语，是英语表达准确性的基础。",
         [["时态类型", "一般", "进行", "完成", "完成进行"],
          ["现在", "I work", "I am working", "I have worked", "I have been working"],
          ["过去", "I worked", "I was working", "I had worked", "I had been working"],
          ["将来", "I will work", "I will be working", "I will have worked", "I will have been working"]],
         None),
        # source: https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/present-tense
        ("第二讲 一般现在时（Present simple）",
         "一般现在时用于表示习惯性动作、客观事实、普遍真理和固定安排。|第三人称单数作主语时，动词需加-s或-es（如works, goes, studies）。|常与频度副词连用：always, usually, often, sometimes, seldom, never。这些副词通常放在实义动词前，be动词或助动词后。|The earth revolves around the sun.（客观真理）I usually get up at seven.（习惯）",
         [["用法", "例句", "时间状语"], ["习惯性动作", "I drink coffee every morning.", "every, usually"],
          ["客观事实/真理", "Water boils at 100°C.", "—"],
          ["固定安排", "The train leaves at 6 a.m.", "时刻表"],
          ["状态动词", "She owns a house.", "—"]],
         None),
        # source: https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/present-tense
        ("第三讲 现在进行时（Present continuous）",
         "现在进行时表示说话时正在进行的动作或现阶段正在持续的事情。结构为am/is/are + 动词现在分词。|常与now, at the moment, at present, currently, these days等时间状语连用。|状态动词（如know, like, believe, own, belong to）一般不用进行时，除非表达特殊含义。|The economy is growing fast these days.（现阶段持续）Listen! Someone is knocking at the door.（正在进行）",
         [["用法", "例句", "时间状语"], ["正在进行的动作", "She is reading now.", "now, at the moment"],
          ["现阶段持续", "I am learning French this semester.", "these days"],
          ["已安排的将来", "We are leaving tomorrow.", "将来时间状语"],
          ["状态变化", "The weather is getting cold.", "gradually"]],
         None),
        # source: https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/present-tense
        ("第四讲 现在完成时（Present perfect）",
         "现在完成时表示过去发生的动作对现在造成的影响或持续到现在的状态，结构为have/has + 过去分词。|现在完成时不能与具体的过去时间状语（如yesterday, last year, in 2020）连用，但可以与just, already, yet, ever, never, since, for等连用。|现在完成时与一般过去时的区别：一般过去时只陈述过去的事实，现在完成时强调与现在的关联。|I have lost my key.（钥匙现在还没找到）I lost my key yesterday.（只陈述过去的事实）",
         [["时间状语", "说明", "例句"], ["just", "刚刚", "He has just left."],
          ["already", "已经（肯定）", "I have already finished."],
          ["yet", "还没有（疑问/否定）", "Have you finished yet?"],
          ["ever/never", "曾经/从未", "I have never been to Paris."],
          ["since/for", "自从/持续", "I have lived here for 10 years."]],
         "bar"),
        # source: https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/present-tense
        ("第五讲 现在完成进行时（Present perfect continuous）",
         "现在完成进行时强调一个动作从过去持续到现在，且可能继续进行，结构为have/has been + 动词现在分词。|常与for和since引导的时间状语连用，强调动作的持续性。|与现在完成时的区别：现在完成时更关注动作的结果或完成，现在完成进行时更关注动作的持续过程。|I have been reading this book for two hours.（强调读了两小时这个过程，可能还没读完）I have read three chapters.（强调结果——读了三章）",
         [["对比项", "现在完成时", "现在完成进行时"], ["结构", "have + 过去分词", "have been + 现在分词"],
          ["侧重点", "结果/完成", "持续过程"],
          ["时间状语", "already, just, ever", "for, since, all day"],
          ["例句", "I have written three letters.", "I have been writing letters."]],
         None),
        # source: https://www.superprof.co.uk/blog/explain-tenses-english/
        ("第六讲 一般过去时（Past simple）",
         "一般过去时表示过去某个具体时间发生的动作或存在的状态，常与yesterday, last week, in 2020, ago等时间状语连用。|规则动词加-ed构成过去式：work→worked, like→liked, study→studied, stop→stopped。|不规则动词需单独记忆：go→went, take→took, see→saw, come→came。|规则动词-ed的发音规则：在清辅音后读/t/（worked），在浊辅音和元音后读/d/（played），在t和d后读/ɪd/（wanted）。",
         [["动词类型", "变化方式", "示例"], ["一般规则", "加-ed", "work → worked"],
          ["以e结尾", "加-d", "like → liked"],
          ["辅音字母+y结尾", "变y为i加-ed", "study → studied"],
          ["重读闭音节结尾", "双写末辅音加-ed", "stop → stopped"],
          ["不规则动词", "需记忆", "go → went, take → took"]],
         None),
        # source: https://www.superprof.co.uk/blog/explain-tenses-english/
        ("第七讲 过去进行时（Past continuous）",
         "过去进行时表示过去某一时刻或某段时间正在进行的动作，结构为was/were + 动词现在分词。|常用于描述过去某动作发生时的背景：I was reading when the phone rang.（read是背景动作，ring是打断动作）|while引导的时间状语从句常用过去进行时，when引导的从句则常用一般过去时。|While I was cooking, he came home.（cook是背景，come是打断）",
         [["从句连词", "主句时态", "从句时态"], ["when", "一般过去时", "过去进行时"],
          ["while", "过去进行时", "一般过去时"],
          ["as", "过去进行时", "过去进行时"]],
         None),
        # source: https://www.superprof.co.uk/blog/explain-tenses-english/
        ("第八讲 过去完成时（Past perfect）",
         "过去完成时表示在过去某一时间或某一动作之前已经完成的动作，即过去的过去。结构为had + 过去分词。|常与by the time, before, after, when等引导的状语从句连用。|使用过去完成时的前提是上下文中已有明确的过去时间参照点，否则不需要使用。|By the time I arrived, the train had left.（arrive是过去，leave是过去的过去）",
         [["时间参照", "过去完成时用法", "例句"], ["by + 过去时间", "到过去某时已完成", "By 2020, I had graduated."],
          ["before + 过去动作", "在另一过去动作之前", "He had left before I arrived."],
          ["after + 过去完成时", "主句用一般过去时", "After I had finished, I went home."]],
         None),
        # source: https://www.superprof.co.uk/blog/explain-tenses-english/
        ("第九讲 过去完成进行时（Past perfect continuous）",
         "过去完成进行时表示过去某一时间之前一直持续的动作，结构为had been + 动词现在分词。|强调动作在过去的某一时间点之前持续了多久。|与过去完成时的区别：过去完成时强调完成，过去完成进行时强调持续。|I had been waiting for two hours when he finally arrived.（强调等待持续了两小时，直到他来）",
         [["时态", "侧重点", "例句"],
          ["过去完成时", "已完成", "I had finished the work."],
          ["过去完成进行时", "持续过程", "I had been working for hours."]],
         None),
        # source: https://www.superprof.co.uk/blog/explain-tenses-english/
        ("第十讲 一般将来时（Future simple）",
         "一般将来时表示将来某个时间将要发生的动作或状态。结构为will/shall + 动词原形，或be going to + 动词原形。|will侧重即时决定或预测，be going to侧重计划安排或根据目前迹象推断即将发生的事。|现在进行时也可表示按计划即将发生的动作，常用于go, come, leave, arrive等位移动词。|Look at the clouds. It is going to rain.（根据迹象）I will help you with your homework.（即时决定）",
         [["结构", "用法", "例句"], ["will + 动词原形", "即时决定、预测", "I will help you."],
          ["be going to + 动词原形", "计划、迹象", "It is going to rain."],
          ["现在进行时", "按计划即将发生", "We are leaving tomorrow."],
          ["一般现在时", "时刻表、日程", "The train leaves at 6."]],
         None),
        # source: https://www.superprof.co.uk/blog/explain-tenses-english/
        ("第十一讲 将来进行时（Future continuous）",
         "将来进行时表示将来某一时刻正在进行的动作，结构为will be + 动词现在分词。|常与this time tomorrow, at 8 p.m. tonight, at this time next week等时间状语连用。|也可表示按计划即将发生的动作，语气比一般将来时更委婉。|This time tomorrow, I will be flying to London.（明天此时正在飞往伦敦）",
         [["用法", "例句", "时间状语"], ["将来某时刻正在进行的动作", "I will be working at 10 a.m.", "at 10 a.m."],
          ["按计划即将发生", "We will be having dinner soon.", "soon"],
          ["委婉语气", "I will be helping you with that.", "—"]],
         None),
        # source: https://www.superprof.co.uk/blog/explain-tenses-english/
        ("第十二讲 将来完成时（Future perfect）",
         "将来完成时表示到将来某一时间点之前已经完成的动作，结构为will have + 过去分词。|常与by引导的时间状语连用，如by tomorrow, by next year, by 2030等。|强调在未来某个时间点之前动作已经完成。|By the end of this year, I will have finished this project.（到今年年底之前完成）",
         [["时间状语", "说明", "例句"], ["by + 将来时间", "到将来某时已完成", "By 2025, I will have graduated."],
          ["by the time + 将来从句", "到将来某时", "By the time you arrive, I will have left."]],
         None),
        # source: https://www.superprof.co.uk/blog/explain-tenses-english/
        ("第十三讲 将来完成进行时（Future perfect continuous）",
         "将来完成进行时表示到将来某一时间点为止一直持续的动作，结构为will have been + 动词现在分词。|常与by引导的时间状语连用，强调动作从过去或现在持续到将来某时。|By next month, I will have been learning English for ten years.（到下个月学英语就满十年了）|这一时态在日常使用中较少，但在正式写作中仍有价值。",
         [["结构", "用法", "例句"], ["will have been + 现在分词", "到将来某时一直持续的动作", "I will have been working here for 5 years by 2025."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第十四讲 名词与冠词",
         "英语名词分为可数与不可数两类。可数名词单数前通常需要限定词，不可数名词一般不加不定冠词。|定冠词the表示特指，不定冠词a/an表示泛指，零冠词多用于泛指复数或不可数概念。|a用于以辅音音素开头的词前，an用于以元音音素开头的词前。注意是音素而非字母：an hour（h不发音），a university（u发/juː/）。",
         [["用法", "示例", "说明"], ["a/an", "a book, an apple", "泛指单数可数名词"],
          ["the", "the book on the desk", "特指双方已知事物"],
          ["零冠词", "Water is essential.", "泛指不可数名词"]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第十五讲 代词",
         "人称代词有主格与宾格之分：主格作主语，宾格作宾语。|形容词性物主代词后必须接名词，名词性物主代词则单独使用。|反身代词由形容词性物主代词加-self/-selves构成，用于强调或表示动作回到主语本身。",
         [["类型", "单数", "复数"], ["主格", "I / you / he / she / it", "we / you / they"],
          ["宾格", "me / you / him / her / it", "us / you / them"],
          ["形容词性物主代词", "my / your / his / her / its", "our / your / their"],
          ["名词性物主代词", "mine / yours / his / hers", "ours / yours / theirs"]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第十六讲 被动语态",
         "被动语态表示主语是动作的承受者，基本结构为be + 过去分词。|执行者需强调时用by引出，否则通常省略。|不及物动词和不及物动词短语（如happen, occur, take place, belong to）没有被动语态。",
         [["时态", "主动语态", "被动语态"], ["一般现在时", "They clean the room.", "The room is cleaned."],
          ["一般过去时", "They cleaned the room.", "The room was cleaned."],
          ["现在完成时", "They have cleaned it.", "It has been cleaned."],
          ["一般将来时", "They will clean it.", "It will be cleaned."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第十七讲 定语从句",
         "定语从句修饰名词或代词，由关系代词（who, whom, whose, which, that）或关系副词（when, where, why）引导。|关系代词在从句中作宾语时可以省略，作主语时不能省略。|非限制性定语从句用逗号隔开，提供补充信息，不能用that引导。",
         [["先行词", "关系代词", "例句"], ["人", "who / whom / that", "The man who called is my uncle."],
          ["物", "which / that", "The book which I bought is useful."],
          ["人或物（所有格）", "whose", "The girl whose bag was lost is crying."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第十八讲 虚拟语气",
         "虚拟语气表示与事实相反的假设、愿望或建议。与现在事实相反时，从句用过去式，主句用would/could/might + 动词原形。|与过去事实相反时，从句用had + 过去分词，主句用would have + 过去分词。|wish后接虚拟语气：I wish I were taller.（与现在相反）I wish I had studied harder.（与过去相反）",
         [["时间", "if从句", "主句"], ["与现在相反", "did / were", "would do"],
          ["与过去相反", "had done", "would have done"], ["与将来相反", "were to do / should do", "would do"]],
         "bar"),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第十九讲 介词搭配",
         "介词搭配是英语学习的难点，多数需要整体记忆而非依赖规则推导。|同一动词搭配不同介词往往产生完全不同的含义。|介词后接动名词，不能直接接不定式：I'm good at swimming（不能用to swim）。",
         [["短语", "含义", "例句"], ["look after", "照顾", "She looks after her sister."],
          ["look for", "寻找", "I am looking for my keys."],
          ["look into", "调查", "We will look into it."],
          ["look forward to", "期待", "I look forward to your reply."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十讲 常见中式英语错误",
         "中式英语多源于直接套用中文语序或用词。识别并纠正这些习惯能显著提升表达的准确性。|写作时应注意主谓一致、时态统一以及冠词的使用。|中文思维直译是中式英语的根源，应通过大量阅读原版材料培养英语语感。",
         [["错误表达", "正确表达", "说明"], ["I very like it.", "I like it very much.", "very不直接修饰动词"],
          ["He is very good at speak English.", "He is very good at speaking English.", "介词后接动名词"],
          ["Although it is raining, but I go out.", "Although it is raining, I go out.", "although与but不同现"],
          ["I have gone to Beijing last year.", "I went to Beijing last year.", "明确过去时间用一般过去时"]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十一讲 情态动词",
         "情态动词表示能力、许可、义务、推测等意义，后接动词原形，无人称和数的变化。|can/could表示能力和可能；may/might表示许可和推测；must表示义务和强烈推测；should/ought to表示建议和期望。|情态动词的推测用法：must be（一定），can't be（不可能），may be（可能）。对过去的推测用情态动词 + have + 过去分词。",
         [["情态动词", "主要含义", "例句"], ["can/could", "能力、许可、可能", "She can swim."],
          ["may/might", "许可、推测", "It may rain tomorrow."],
          ["must", "义务、强烈推测", "You must stop."],
          ["should/ought to", "建议、期望", "You should rest."], ["needn't", "不必", "You needn't come."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十二讲 非谓语动词概述",
         "非谓语动词包括不定式（to do）、动名词（doing）和分词（doing/done），它们不受主语人称和数的限制。|不定式常表示目的、将来或具体的动作；动名词常表示习惯性、抽象的概念；分词常作定语或状语。|选择哪种非谓语形式取决于它在句中的功能以及与逻辑主语的语态关系（主动用doing/被动用done）。",
         [["形式", "构成", "主要功能"], ["不定式", "to + 动词原形", "目的、主语、宾语、补语"],
          ["动名词", "动词 + ing", "主语、宾语、介词宾语"],
          ["现在分词", "动词 + ing", "定语、状语（主动进行）"],
          ["过去分词", "动词 + ed/不规则", "定语、状语（被动完成）"]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十三讲 动名词",
         "动名词具有名词性质，可作主语、宾语、表语和定语。|有些动词后只能接动名词作宾语：enjoy, finish, avoid, mind, suggest, practice, consider, deny, escape, imagine等。|有些动词后接动名词和不定式含义不同：remember doing（记得做过），remember to do（记得去做）；stop doing（停止做），stop to do（停下来去做）。",
         [["动词后接动名词", "例句"], ["enjoy", "I enjoy reading novels."],
          ["avoid", "He avoided answering the question."], ["finish", "She finished writing the report."],
          ["mind", "Would you mind opening the window?"], ["practice", "They practice playing the piano."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十四讲 现在分词",
         "现在分词表示主动和进行，可作定语、表语、宾语补足语和状语。|作定语时：a crying baby（正在哭的婴儿），the boiling water（沸腾的水）。|作状语时表示时间、原因、条件、结果和伴随状态：Walking in the park, I met an old friend.（时间状语）",
         [["功能", "例句", "说明"], ["定语", "a sleeping dog", "主动进行"],
          ["表语", "The news is exciting.", "令人兴奋的"],
          ["宾补", "I saw him crossing the street.", "动作正在进行"],
          ["状语", "Hearing the news, she smiled.", "时间/原因/伴随"]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十五讲 过去分词",
         "过去分词表示被动和完成，可作定语、表语、宾语补足语和状语。|及物动词的过去分词表示被动含义；不及物动词的过去分词表示完成含义。|过去分词作状语：Given more time, I could do it better.（条件状语，被动含义）",
         [["功能", "例句", "说明"], ["定语", "a broken window", "被打破的窗"],
          ["表语", "I am interested in music.", "感到兴趣"],
          ["宾补", "I had my hair cut.", "使某事被做"],
          ["状语", "Punished by the teacher, he cried.", "原因状语，被动"]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十六讲 不定式",
         "不定式可在句中作主语、宾语、表语、定语、状语和补语。|有些动词后只能接不定式作宾语：decide, hope, expect, promise, agree, refuse, manage, offer, fail, pretend等。|不定式的进行式（to be doing）表示与谓语动词同时进行的动作；完成式（to have done）表示在谓语动词之前已完成的动作。",
         [["功能", "例句"], ["主语", "To learn English is important."],
          ["宾语", "I decided to leave early."], ["表语", "My goal is to become a doctor."],
          ["定语", "I have something to tell you."], ["状语（目的）", "He came to help me."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十七讲 主谓一致",
         "主谓一致是指谓语动词在人称和数上与主语保持一致。英语有三种一致原则：语法一致、意义一致和就近一致。|集合名词（family, team, committee等）作主语时，强调整体用单数，强调个体成员用复数。|either...or, neither...nor, not only...but also连接两个主语时，谓语动词与靠近的主语一致（就近原则）。",
         [["主语类型", "谓语", "例句"], ["集合名词（整体）", "单数", "My family is large."],
          ["集合名词（成员）", "复数", "My family are watching TV."],
          ["either A or B", "与B一致", "Either you or he is right."],
          ["each/every + 单名", "单数", "Each student has a book."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十八讲 倒装句",
         "倒装分为完全倒装（整个谓语提到主语前）和部分倒装（助动词/情态动词提到主语前）。|否定词或含否定意义的词位于句首时用部分倒装：Never have I seen such a beautiful place.|Only + 状语位于句首时也用部分倒装：Only then did I realize my mistake.",
         [["倒装类型", "触发条件", "例句"], ["部分倒装", "否定词前置", "Never have I been there."],
          ["部分倒装", "Only + 状语前置", "Only by working hard can we succeed."],
          ["部分倒装", "So + 形容词/副词前置", "So tired was he that he fell asleep."],
          ["完全倒装", "地点/方位副词前置", "Here comes the bus."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第二十九讲 强调句型",
         "强调句型结构为It is/was + 被强调部分 + that/who + 句子其余部分。|可以强调主语、宾语、状语等，但不能强调谓语动词。强调人时可用who或that，强调物时用that。|判断是否为强调句的方法：去掉It is/was和that/who后，句子结构仍然完整通顺。",
         [["强调成分", "例句", "还原句"], ["主语", "It was Tom who broke the window.", "Tom broke the window."],
          ["宾语", "It was the window that Tom broke.", "Tom broke the window."],
          ["状语", "It was yesterday that he came.", "He came yesterday."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第三十讲 名词性从句",
         "名词性从句在句中起名词作用，可作主语、宾语、表语和同位语。由that, whether/if, what, who, which, when, where, how, why等引导。|that引导名词性从句时不充当句子成分，仅起连接作用，在宾语从句中常可省略。|whether和if都可表示是否，但whether可用于所有名词性从句，if主要用于宾语从句且不能与or not连用。",
         [["从句类型", "引导词", "例句"], ["主语从句", "that, whether", "That he is honest is true."],
          ["宾语从句", "that, if, what", "I know that he is right."],
          ["表语从句", "that, what, because", "The truth is that I forgot."],
          ["同位语从句", "that", "The news that he won is exciting."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第三十一讲 状语从句概述",
         "状语从句在句中作状语，修饰动词、形容词或副词，由从属连词引导。按意义分为时间、地点、原因、条件、目的、结果、让步、方式、比较九种。|状语从句的位置可在主句前（用逗号隔开）或主句后（不用逗号）。|使用状语从句时应注意时态呼应：主句用将来时，时间/条件状语从句用现在时表将来。",
         [["类型", "常用连词"], ["时间", "when, while, as, before, after, since, until"],
          ["原因", "because, as, since, for"], ["条件", "if, unless, as long as"],
          ["目的", "so that, in order that"], ["结果", "so...that, such...that"],
          ["让步", "although, though, even though"], ["方式", "as, as if, as though"]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第三十二讲 条件状语从句",
         "条件状语从句分为真实条件句（第一条件句）和非真实条件句（虚拟语气）。|真实条件句：if + 一般现在时，主句用will/can/may + 动词原形。If it rains tomorrow, I will stay home.|unless = if not，意为除非。As long as = if only，意为只要。",
         [["类型", "if从句时态", "主句时态", "例句"], ["真实条件句", "一般现在时", "will + 动词原形", "If you study, you will pass."],
          ["虚拟（现在）", "过去式", "would + 动词原形", "If I were rich, I would travel."],
          ["虚拟（过去）", "had + 过去分词", "would have + 过去分词", "If I had known, I would have helped."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第三十三讲 让步与原因状语从句",
         "让步状语从句表示虽然、尽管、即使等让步意义，由although, though, even though, even if, while, no matter等引导。|although和though用法基本相同，但though可作副词放句末表示不过，而although不能。|原因状语从句由because, as, since, for, now that等引导。because语气最强，回答why提问；as和since语气较弱，通常放在句首，表示已知的、显然的原因。",
         [["连词", "含义", "例句"], ["although/though", "虽然", "Although it was late, he kept working."],
          ["even though", "即使（事实）", "Even though he was tired, he continued."],
          ["even if", "即使（假设）", "Even if it rains, I will go."],
          ["because", "因为（最强）", "I did it because I had to."],
          ["since/as", "既然/因为（较弱）", "Since you are here, let's start."]],
         None),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第三十四讲 比较级与最高级",
         "形容词和副词的比较级用于两者之间的比较，最高级用于三者或以上的比较。|短词（单音节）加-er/-est；长词（多音节）前加more/most。不规则变化：good→better→best, bad→worse→worst, far→farther/further→farthest/furthest。|比较级修饰语：much, a lot, far, even, still, a little, slightly。最高级前通常加the。",
         [["原级", "比较级", "最高级"], ["tall", "taller", "tallest"],
          ["beautiful", "more beautiful", "most beautiful"],
          ["good", "better", "best"], ["bad", "worse", "worst"],
          ["many/much", "more", "most"], ["far", "farther/further", "farthest/furthest"]],
         "bar"),
        # source: general ESL reference (British Council / Cambridge grammar)
        ("第三十五讲 直接引语与间接引语",
         "直接引语是原封不动地引用他人的话，用引号标出。间接引语是用自己的话转述他人的话，不用引号。|直接引语变间接引语时：人称要变化，时态往前推一级，时间/地点状语要调整，疑问句语序变陈述语序。|祈使句的间接引语用tell/ask sb. to do sth.的结构。",
         [["变化项", "直接引语", "间接引语"], ["一般现在时", "I am busy.", "He said he was busy."],
          ["一般过去时", "I saw her.", "He said he had seen her."],
          ["now", "now", "then"], ["today", "today", "that day"], ["tomorrow", "tomorrow", "the next day"]],
         None),
    ],
}
